# Generated by Django 3.0.8 on 2020-09-24 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dead_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 19, 0, 33, 323316), verbose_name='最长可用时间'),
        ),
    ]
