# Generated by Django 3.0.8 on 2020-09-25 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200924_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dead_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最长可用时间'),
        ),
    ]
