# Generated by Django 3.0.8 on 2020-09-24 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('banner', models.CharField(max_length=300, verbose_name='文章标题图片')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('show_comment', models.BooleanField(default=True, verbose_name='展示评论')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='文章密码')),
                ('create_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_date_time'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ArticleToTags',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(max_length=30, verbose_name='标签ID')),
                ('article_id', models.CharField(max_length=30, verbose_name='文章ID')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('article_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='文章ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='草稿内容')),
                ('type', models.IntegerField(choices=[(0, '自动保存'), (1, '手动保存'), (2, '热保存')], default=0, verbose_name='类型')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-create_date_time'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='tag名称')),
                ('color', models.CharField(max_length=30, verbose_name='颜色')),
                ('create_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
    ]
