# Generated by Django 3.0.8 on 2020-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_access_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=300),
        ),
    ]
